In [1]:
import docx2txt

# Set the path to your input and output files
input_file = 'C://temp//Repertoriummetoudepersoonsnummers.docx'
temp_file = 'C://temp//temp.txt'

# Use docx2txt library to extract text from .docx file
text = docx2txt.process(input_file)

# Write the extracted text to a .txt file
with open(temp_file, 'w', encoding='utf-8') as f:
    f.write(text)

In [2]:
output_file = 'C://temp//output.txt'

In [3]:
with open(temp_file, 'r', encoding='utf-8') as file:
    data = file.read()

# Replace newlines with semicolons
data = data.replace('\n\n', ';')

# Remove excessive whitespaces
data = ' '.join(data.split())

# Replace semicolons with newlines and add semicolons between name and details
data = data.replace('; ', ';\n').replace(';','; ')

In [4]:
output_file_2 = 'C://temp//output2.txt'
with open(output_file_2, 'w', encoding='utf-8') as f:
    f.write(data)

In [5]:
output_file_3 = 'C://temp//output3.txt'
output_file_4 = 'C://temp//output4.txt'

In [6]:
with open(output_file_2, "r") as input_file:
    with open(output_file_3, "w") as output_file:
        merged_line = ''
        for line in input_file:
            if '<'and'>' in line:
                # if <x> is present, write the merged line to output file and reset the merged_line
                output_file.write(merged_line + line.strip() + '\n')
                merged_line = ''
            else:
                # otherwise merge the current line to the merged_line
                merged_line += line.strip() + ' '

In [7]:
with open(output_file_3, "r") as f_in:
    with open(output_file_4, "w") as f_out:
        for line in f_in:
            if line.startswith("; "):
                line = line[2:]
            f_out.write(line)

In [8]:
import csv

input_file = output_file_4
output_file = 'C://temp//output_file.csv'

# Define the headers for the output file
headers = ['Surname', 'Name', 'Field 3', 'Field 4', 'Field 5', 'Field 6', 'Field 7', 'Field 8', 'Field 9', 'Field 10', 'Field 11', 'Field 12', 'Field 13']

with open(input_file, 'r') as infile, open(output_file, 'w', newline='') as outfile:
    reader = csv.reader(infile, delimiter=';')
    writer = csv.writer(outfile)
    
    # Write the headers to the output file
    writer.writerow(headers)

    # Loop through each row in the input file and write it to the output file with 12 fields
    for row in reader:
        # Create a new row with 12 fields by extending the current row with empty values
        new_row = row + [''] * (12 - len(row))
        writer.writerow(new_row)

In [16]:
import pandas as pd

In [18]:
df = pd.read_csv(output_file)
df.head(100)

,Surname,Name,Field 3,Field 4,Field 5,Field 6,Field 7,Field 8,Field 9,Field 10,Field 11,Field 12,Field 13
0,"Aalburg, van",Johannes,Geb. Zierikzee ca. 1717,"pred. Oudkarspel 30 juni 1743, overl. 14 maar...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aalst,Wilhelmus,Gedoopt Biggekerke 5 jan. 1664,"pred. Aardenburg 22 mei 1695, overl. 19 dec. ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Aalst, van",Cornelius,Geb. Castricum ca. 1686,ambassadepred. in Parijs maart tot dec. 1715,"pred. Kalslagen ber. 21 febr. 1717, emer. 1751",overl. Amsterdam 27 aug. 1756.<2>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Aalst, van",Gerardus,Geb. xxx sept. 1678,"pred. Vuren en Dalem 10 aug. 1704, Sommelsdij...",overl. 29 juni 1759.<3>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aalstius,Henricus,Geb. 's-Hertogenbosch (?) yyy,"pred. Castricum en Heemskerk nov. 1700, emer....",overl. Limmen 15 maart 1736.<5>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"Adena, van",Wilhelmus,Geb. Harderwijk ca. 1589,waarnemend pred. Arnhem 1625,"pred. Hall + Loenen (Gld) 1626, Hall 1653, ov...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,Adius,Quirinus,Geb. xxx 26 aug. 1701,"pred. Oenkerk, Giekerk en Wijns juli 1723, af...",overl. nov. 1739.<89>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Adolphi,Ypeus,Geb. Witmarsum yyy,pred. Hijlaard en Lyons (tot 1637 met Huins) ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Adriaanse,Geleyn,Geb. xxx yyy,"pred. Wemeldinge 1 dec. 1578, overl. 12 maart...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Adriaansz.,Cornelis,Geb. (verm. Holland) yyy,"snijder, later lakenkoper te Vlaardingen (div...","pred. Dirksland 1595, Maassluis 1598, overl. ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df['born'] = df.apply(lambda row: row[row.astype(str).str.contains('Geb.')].iloc[0] if any(row.astype(str).str.contains('Geb.')) else '', axis=1)
df['predikant'] = df.apply(lambda row: row[row.astype(str).str.contains('pred.')].iloc[0] if any(row.astype(str).str.contains('Geb.')) else '', axis=1)

In [26]:
df.head(100)

,Surname,Name,Field 3,Field 4,Field 5,Field 6,Field 7,Field 8,Field 9,Field 10,Field 11,Field 12,Field 13,born,predikant
0,"Aalburg, van",Johannes,Geb. Zierikzee ca. 1717,"pred. Oudkarspel 30 juni 1743, overl. 14 maar...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geb. Zierikzee ca. 1717,"pred. Oudkarspel 30 juni 1743, overl. 14 maar..."
1,Aalst,Wilhelmus,Gedoopt Biggekerke 5 jan. 1664,"pred. Aardenburg 22 mei 1695, overl. 19 dec. ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
2,"Aalst, van",Cornelius,Geb. Castricum ca. 1686,ambassadepred. in Parijs maart tot dec. 1715,"pred. Kalslagen ber. 21 febr. 1717, emer. 1751",overl. Amsterdam 27 aug. 1756.<2>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geb. Castricum ca. 1686,ambassadepred. in Parijs maart tot dec. 1715
3,"Aalst, van",Gerardus,Geb. xxx sept. 1678,"pred. Vuren en Dalem 10 aug. 1704, Sommelsdij...",overl. 29 juni 1759.<3>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geb. xxx sept. 1678,"pred. Vuren en Dalem 10 aug. 1704, Sommelsdij..."
4,Aalstius,Henricus,Geb. 's-Hertogenbosch (?) yyy,"pred. Castricum en Heemskerk nov. 1700, emer....",overl. Limmen 15 maart 1736.<5>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geb. 's-Hertogenbosch (?) yyy,"pred. Castricum en Heemskerk nov. 1700, emer...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"Adena, van",Wilhelmus,Geb. Harderwijk ca. 1589,waarnemend pred. Arnhem 1625,"pred. Hall + Loenen (Gld) 1626, Hall 1653, ov...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geb. Harderwijk ca. 1589,waarnemend pred. Arnhem 1625
96,Adius,Quirinus,Geb. xxx 26 aug. 1701,"pred. Oenkerk, Giekerk en Wijns juli 1723, af...",overl. nov. 1739.<89>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geb. xxx 26 aug. 1701,"pred. Oenkerk, Giekerk en Wijns juli 1723, af..."
97,Adolphi,Ypeus,Geb. Witmarsum yyy,pred. Hijlaard en Lyons (tot 1637 met Huins) ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geb. Witmarsum yyy,pred. Hijlaard en Lyons (tot 1637 met Huins) ...
98,Adriaanse,Geleyn,Geb. xxx yyy,"pred. Wemeldinge 1 dec. 1578, overl. 12 maart...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geb. xxx yyy,"pred. Wemeldinge 1 dec. 1578, overl. 12 maart..."
99,Adriaansz.,Cornelis,Geb. (verm. Holland) yyy,"snijder, later lakenkoper te Vlaardingen (div...","pred. Dirksland 1595, Maassluis 1598, overl. ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geb. (verm. Holland) yyy,"pred. Dirksland 1595, Maassluis 1598, overl. ..."